"use client";
import {useMemo,useState} from "react";
const versions:any={essentiel:{label:'Essentiel',price:3990},confort:{label:'Confort',price:4990},confortPlus:{label:'Confort Plus',price:5990}};
const zones:any={350:['31','81','82','32','09'],490:['11','12','46','47','33','65','66','34','30','40','24','19','87','15'],690:['75','77','78','91','92','93','94','95','13','69','63','16','17','86'],790:['44','35','56','29','22','53','49','67','68']};
function delivery(cp:string,ret:boolean){if(ret)return 0;const d=cp.slice(0,2);for(const [p,ds] of Object.entries(zones))if((ds as string[]).includes(d))return Number(p);return 790}
export default function Page(){const[version,setVersion]=useState('confort');const[cp,setCp]=useState('');const[ret,setRet]=useState(false);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[done,setDone]=useState<any>(null);const transport=useMemo(()=>delivery(cp,ret),[cp,ret]);const total=versions[version].price+150+transport;
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMsg('Analyse du COC et création de votre dossier…');try{const fd=new FormData(e.currentTarget);fd.set('version',version);fd.set('quantity','1');fd.set('registration_fee','150');fd.set('delivery_fee',String(transport));fd.set('service_carte_grise','oui');const r=await fetch('/api/erp/sale-from-coc',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Envoi impossible');setDone(j);setMsg('✅ Vente enregistrée et dossier carte grise ouvert.');}catch(e){setMsg(`❌ ${e instanceof Error?e.message:'Erreur'}`)}finally{setLoading(false)}}
if(done)return <main style={main}><div style={success}><h1>Merci, votre commande est enregistrée.</h1><p>Votre COC a été reçu et le dossier d’immatriculation est maintenant ouvert chez NeoDrive.</p><p><b>Commande : {done.orderNumber}</b></p>{done.vin&&<p>VIN identifié : <b>{done.vin}</b></p>}<p>Nous poursuivons maintenant les démarches de carte grise. Conservez votre numéro de commande.</p></div></main>;
return <main style={main}><div style={{maxWidth:850,margin:'0 auto'}}><h1>Réservation NeoDrive + Carte grise</h1><p style={lead}>Un seul dossier : vos coordonnées, votre COC et les justificatifs nécessaires. <b>L’envoi du dossier avec le COC confirme la vente</b> et déclenche le traitement de la carte grise.</p><form onSubmit={submit} style={{display:'grid',gap:18}}><section style={box}><h2>1. Votre véhicule</h2><label>Version<select name="version" value={version} onChange={e=>setVersion(e.target.value)} style={input}><option value="essentiel">Essentiel — 3 990 € TTC</option><option value="confort">Confort — 4 990 € TTC</option><option value="confortPlus">Confort Plus — 5 990 € TTC</option></select></label><div style={price}><span>Véhicule</span><b>{versions[version].price} €</b><span>Pack carte grise / mise en route</span><b>150 €</b><span>Livraison</span><b>{transport} €</b><span>Total indicatif</span><strong>{total} € TTC</strong></div></section>
<section style={box}><h2>2. Coordonnées du titulaire</h2><div style={two}><Field n="prenom" p="Prénom"/><Field n="nom" p="Nom"/><Field n="telephone" p="Téléphone"/><Field n="email" p="E-mail" type="email"/><Field n="adresse" p="Adresse" wide/><label>Code postal<input name="code_postal" required value={cp} onChange={e=>setCp(e.target.value)} style={input}/></label><Field n="ville" p="Ville"/></div><label style={{display:'flex',gap:8,marginTop:14}}><input type="checkbox" checked={ret} onChange={e=>setRet(e.target.checked)}/> Retrait sur place</label></section>
<section style={box}><h2>3. COC — document qui rattache la vente au véhicule</h2><p>Le système lit automatiquement le certificat, identifie le VIN et rattache votre dossier au véhicule correspondant.</p><label style={upload}>Certificat de conformité européen (COC) — obligatoire<input type="file" name="coc" accept=".pdf,image/*" required/></label></section>
<section style={box}><h2>4. Documents carte grise</h2><label style={upload}>Pièce d’identité<input type="file" name="cni" accept=".pdf,image/*" required/></label><label style={upload}>Justificatif de domicile<input type="file" name="justificatif_domicile" accept=".pdf,image/*" required/></label><label style={upload}>Mandat carte grise signé<input type="file" name="mandat_carte_grise_signe" accept=".pdf,image/*"/></label><label style={upload}>Devis / bon de commande signé<input type="file" name="devis_signe" accept=".pdf,image/*"/></label><label style={upload}>CNIT / homologation si disponible<input type="file" name="cnit" accept=".pdf,image/*"/></label></section>
<button disabled={loading} style={submitBtn}>{loading?'Traitement en cours…':'Confirmer la commande et lancer la carte grise'}</button>{msg&&<p style={{fontWeight:800}}>{msg}</p>}<p style={{fontSize:13,color:'#666'}}>Les documents sont enregistrés dans le dossier interne NeoDrive. Le COC est utilisé pour identifier le véhicule et créer le suivi administratif.</p></form></div></main>}
function Field({n,p,type='text',wide=false}:any){return <label style={wide?{gridColumn:'1/-1'}:{}}>{p}<input name={n} type={type} required style={input}/></label>}
const main:React.CSSProperties={minHeight:'100vh',padding:'38px 18px 70px',fontFamily:'Arial,sans-serif',background:'#f7f7f5',color:'#151515'};const lead:React.CSSProperties={fontSize:18,lineHeight:1.55,color:'#444'};const box:React.CSSProperties={background:'#fff',padding:22,borderRadius:16,border:'1px solid #e2e2df'};const two:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14};const input:React.CSSProperties={display:'block',width:'100%',boxSizing:'border-box',marginTop:7,padding:12,border:'1px solid #ccc',borderRadius:9,fontSize:16};const upload:React.CSSProperties={display:'grid',gap:8,padding:14,marginTop:10,border:'1px dashed #aaa',borderRadius:10,fontWeight:700};const price:React.CSSProperties={display:'grid',gridTemplateColumns:'1fr auto',gap:10,marginTop:18,padding:15,background:'#f5f5f3',borderRadius:12};const submitBtn:React.CSSProperties={padding:'17px 20px',border:0,borderRadius:12,background:'#111',color:'#fff',fontSize:18,fontWeight:900,cursor:'pointer'};const success:React.CSSProperties={maxWidth:700,margin:'80px auto',padding:30,background:'#fff',borderRadius:18,border:'1px solid #ddd'};
