import { NextResponse } from "next/server";
import OpenAI from "openai";
export const dynamic="force-dynamic";export const maxDuration=60;
const SB="https://tzlsdjzcxdjaatcpwqwn.supabase.co";const H=(k:string)=>({Authorization:`Bearer ${k}`,apikey:k,"Content-Type":"application/json"});
const slots=[{h:9,m:30},{h:13,m:30},{h:18,m:30}];
function parisIso(day:number,h:number,m:number){const d=new Date(Date.now()+day*86400000);const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d).map(x=>[x.type,x.value]));const local=`${p.year}-${p.month}-${p.day}T${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:00`;const summer=new Date().getTimezoneOffset();return new Date(local+((new Date(`${p.year}-07-01`).getTimezoneOffset()===summer)?"+02:00":"+01:00")).toISOString();}
function isVideo(a:any){return /video|reel/i.test(a.media_type)||/\.(mp4|mov|m4v)(\?|$)/i.test(a.public_url||"");}
export async function GET(req:Request){
 const secret=process.env.CRON_SECRET;if(!secret||req.headers.get("authorization")!==`Bearer ${secret}`)return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!k)return NextResponse.json({ok:false,error:"Supabase missing"},{status:503});
 const countR=await fetch(`${SB}/rest/v1/social_content_queue?status=eq.scheduled&publish_at=gte.${encodeURIComponent(new Date().toISOString())}&select=id`,{headers:{...H(k),Prefer:"count=exact"},cache:"no-store"});const existing=Number(countR.headers.get("content-range")?.split("/")[1]||0);if(existing>=18)return NextResponse.json({ok:true,skipped:true,reason:"Queue already stocked",scheduled:existing});
 const [ar,tr]=await Promise.all([fetch(`${SB}/rest/v1/social_media_assets?status=eq.ready&select=id,public_url,media_type,title,context,times_used,priority,ai_quality_score&order=priority.desc,ai_quality_score.desc.nullslast,times_used.asc.nullsfirst,last_used_at.asc.nullsfirst&limit=50`,{headers:H(k),cache:"no-store"}),fetch(`${SB}/rest/v1/marketing_topics?status=eq.idea&select=id,topic,angle,pillar,target_audience,business_priority,times_used&order=business_priority.desc,times_used.asc&limit=30`,{headers:H(k),cache:"no-store"})]);
 const assets=await ar.json(),topics=await tr.json();if(!Array.isArray(assets)||!assets.length)return NextResponse.json({ok:true,skipped:true,reason:"No media"});const vids=assets.filter(isVideo),imgs=assets.filter((a:any)=>!isVideo(a));const c=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;const rows:any[]=[];
 for(let day=0;day<4;day++)for(let s=0;s<3;s++){
  const preferVideo=s===0||s===2;const pool=preferVideo&&vids.length?vids:imgs.length?imgs:assets;const asset=pool[(day*3+s)%pool.length];const topic=Array.isArray(topics)&&topics.length?topics[(day*3+s)%topics.length]:null;const type=isVideo(asset)?"reel":"post";let hook=topic?.topic||["À partir de 3 990 € : une autre façon de penser la voiture sans permis","Petite dehors. Utile au quotidien.","Les coulisses d'une NeoDrive avant livraison"][s];let caption=`${hook}\n\nNeoDrive : voiture sans permis électrique 2 places, à partir de 3 990 € TTC. Recharge sur prise 220 V.\n\n#NeoDrive #VoitureSansPermis #VSP #MobiliteElectrique`;
  if(c)try{const r=await c.responses.create({model:process.env.OPENAI_SOCIAL_MODEL||"gpt-4.1-mini",input:`Légende sociale française pour un vrai média NeoDrive. Sujet:${hook}. Angle:${topic?.angle||"usage réel"}. Média:${asset.title||asset.media_type}. Contexte:${asset.context||"aucun"}. Faits sûrs: VSP électrique 2 places, à partir de 3 990 € TTC, recharge 220 V. 2-5 phrases naturelles, hook concret, 3-6 hashtags, CTA discret. Ne jamais inventer autonomie, sécurité, stock, garantie, avis ou droit de conduire. Retourne seulement la légende.`,max_output_tokens:250});caption=r.output_text.trim()||caption;}catch{}
  for(const platform of ["instagram","facebook"])rows.push({topic_id:topic?.id||null,platform,content_type:type,hook,caption,hashtags:[],media_brief:`${type}; ${topic?.pillar||"brand"}; real-media`,media_url:asset.public_url,cta:"easydrive-auto.fr",publish_at:parisIso(day,slots[s].h,slots[s].m),status:"scheduled",requires_human_review:false,retry_count:0,max_retries:3});
 }
 const ins=await fetch(`${SB}/rest/v1/social_content_queue`,{method:"POST",headers:{...H(k),Prefer:"return=minimal"},body:JSON.stringify(rows)});if(!ins.ok)return NextResponse.json({ok:false,error:await ins.text()},{status:500});return NextResponse.json({ok:true,planned:rows.length,existing,generatedReelsAvailable:vids.filter((a:any)=>String(a.context||"").includes("générée automatiquement")).length});
}
