import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import OpenAI from "openai";

export const dynamic="force-dynamic";
export const maxDuration=60;
const SB="https://tzlsdjzcxdjaatcpwqwn.supabase.co";
function safe(s:string){return s.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)}
function money(v:FormDataEntryValue|null){const n=Number(String(v||"0").replace(",","."));return Number.isFinite(n)?n:0}
async function upload(sb:any,file:File,folder:string){const ext=(file.name.split(".").pop()||"bin").toLowerCase();const path=`${folder}/${Date.now()}-${crypto.randomUUID()}-${safe(file.name||`document.${ext}`)}`;const buf=Buffer.from(await file.arrayBuffer());const {error}=await sb.storage.from("erp-documents").upload(path,buf,{contentType:file.type||"application/octet-stream",upsert:false});if(error)throw error;return path;}
async function extractCOC(file:File){const key=process.env.OPENAI_API_KEY;if(!key)return {vin:null,model:null,variant:null,color:null,confidence:0,raw:null};try{const client=new OpenAI({apiKey:key});const b64=Buffer.from(await file.arrayBuffer()).toString("base64");const response=await client.responses.create({model:process.env.OPENAI_DOCUMENT_MODEL||"gpt-5-mini",input:[{role:"user",content:[{type:"input_text",text:"Analyse ce certificat de conformité européen (COC) automobile. Retourne UNIQUEMENT un JSON valide avec {vin, chassis_number, manufacturer, model, variant, version, category, power_kw, max_speed_kmh, color, confidence}. VIN doit être recopié exactement, sans espace. N'invente rien; utilise null si absent."},{type:"input_file",filename:file.name||"coc.pdf",file_data:`data:${file.type||"application/pdf"};base64,${b64}`}]}] as any,max_output_tokens:400});const txt=(response.output_text||"").trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();const j=JSON.parse(txt);return {...j,raw:txt};}catch(e){return {vin:null,model:null,variant:null,color:null,confidence:0,error:e instanceof Error?e.message:"COC extraction failed"};}}

export async function POST(req:Request){
 const sk=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!sk)return NextResponse.json({ok:false,error:"Configuration serveur incomplète"},{status:503});
 const sb=createClient(SB,sk,{auth:{persistSession:false}});const fd=await req.formData();
 const first=String(fd.get("prenom")||"").trim(),last=String(fd.get("nom")||"").trim(),email=String(fd.get("email")||"").trim(),phone=String(fd.get("telephone")||"").trim();
 const coc=fd.get("coc");if(!first||!last||!email||!phone)return NextResponse.json({ok:false,error:"Coordonnées client incomplètes"},{status:400});if(!(coc instanceof File)||!coc.size)return NextResponse.json({ok:false,error:"Le COC est obligatoire pour conclure la vente et lancer la carte grise."},{status:400});
 const now=new Date().toISOString();
 const {data:customer,error:ce}=await sb.from("customers").insert({first_name:first,last_name:last,email,phone,address:String(fd.get("adresse")||""),postal_code:String(fd.get("code_postal")||""),city:String(fd.get("ville")||""),source:"reservation_carte_grise",updated_at:now}).select().single();if(ce)return NextResponse.json({ok:false,error:ce.message},{status:500});
 const cocPath=await upload(sb,coc,`orders/${customer.id}`);const cocAi=await extractCOC(coc);const vin=String(cocAi?.vin||cocAi?.chassis_number||"").replace(/\s+/g,"").toUpperCase();
 let vehicle:any=null;if(vin){const {data}=await sb.from("vehicles").select("*").or(`vin.eq.${vin},chassis_number.eq.${vin}`).maybeSingle();vehicle=data;}
 if(!vehicle){const {data,error}=await sb.from("vehicles").insert({internal_ref:`AUTO-${Date.now()}`,vin:vin||null,chassis_number:vin||null,model:cocAi?.model||null,version:String(fd.get("version")||cocAi?.variant||""),color:cocAi?.color||null,status:"sold",coc_url:cocPath,coc_extracted:cocAi,coc_verified:!!vin,sold_at:now,current_customer_id:customer.id,updated_at:now}).select().single();if(error)return NextResponse.json({ok:false,error:error.message},{status:500});vehicle=data;await sb.from("vehicle_events").insert({vehicle_id:vehicle.id,event_type:"sale_concluded_from_coc",from_status:null,to_status:"sold",metadata:{vin,coc_confidence:cocAi?.confidence||null,source:"reservation_carte_grise",vehicle_created_from_coc:true}});}else{const from=vehicle.status;const {data,error}=await sb.from("vehicles").update({status:"sold",coc_url:cocPath,coc_extracted:cocAi,coc_verified:!!vin,sold_at:now,reserved_at:vehicle.reserved_at||now,current_customer_id:customer.id,updated_at:now}).eq("id",vehicle.id).select().single();if(error)return NextResponse.json({ok:false,error:error.message},{status:500});vehicle=data;await sb.from("vehicle_events").insert({vehicle_id:vehicle.id,event_type:"sale_concluded_from_coc",from_status:from,to_status:"sold",metadata:{vin,coc_confidence:cocAi?.confidence||null,source:"reservation_carte_grise"}});}
 const version=String(fd.get("version")||"");const qty=Math.max(1,Number(fd.get("quantity")||1));const prices:any={essentiel:3990,confort:4990,confortPlus:5990};const vehiclePrice=prices[version]||money(fd.get("vehicle_price"));const delivery=money(fd.get("delivery_fee")||fd.get("transport"));const reg=money(fd.get("registration_fee"))||150;const prep=money(fd.get("preparation_fee"));const discount=money(fd.get("discount"));const total=vehiclePrice*qty+delivery+(reg+prep)*qty-discount;
 const {data:on}=await sb.rpc("next_order_number");const orderNumber=on||`CMD-${Date.now()}`;const {data:order,error:oe}=await sb.from("customer_orders").insert({order_number:orderNumber,customer_id:customer.id,vehicle_id:vehicle.id,version,quantity:qty,vehicle_price:vehiclePrice,preparation_fee:prep,registration_fee:reg,delivery_fee:delivery,discount,total_ttc:total,amount_paid:0,balance_due:total,payment_status:"unpaid",order_status:"sold_registration_started",registration_requested:true,registration_status:"coc_received",source:"reservation_carte_grise",coc_received_at:now,sold_at:now}).select().single();if(oe)return NextResponse.json({ok:false,error:oe.message},{status:500});
 const files:any={};for(const name of ["cni","justificatif_domicile","mandat_carte_grise_signe","devis_signe","cnit"]){const f=fd.get(name);if(f instanceof File&&f.size){const p=await upload(sb,f,`orders/${order.id}`);files[name]=p;await sb.from("order_documents").insert({order_id:order.id,vehicle_id:vehicle.id,document_type:name,storage_path:p});}}
 await sb.from("order_documents").insert({order_id:order.id,vehicle_id:vehicle.id,document_type:"coc",storage_path:cocPath,ai_extracted:cocAi,verified:!!vin});
 const {error:re}=await sb.from("registration_cases").insert({order_id:order.id,vehicle_id:vehicle.id,customer_id:customer.id,status:"to_submit",vin:vin||null,coc_received:true,identity_received:!!files.cni,address_proof_received:!!files.justificatif_domicile,mandate_received:!!files.mandat_carte_grise_signe,cnit_received:!!files.cnit,updated_at:now});if(re)return NextResponse.json({ok:false,error:`Dossier carte grise: ${re.message}`},{status:500});
 const {data:invn}=await sb.rpc("next_invoice_number");const invoiceNumber=invn||`FAC-${Date.now()}`;await sb.from("invoices").insert({invoice_number:invoiceNumber,order_id:order.id,customer_id:customer.id,vehicle_id:vehicle.id,status:"issued",total_ttc:total,amount_paid:0,balance_due:total,metadata:{generated_automatically:true,trigger:"coc_submission"}});
 await sb.from("deliveries").insert({order_id:order.id,vehicle_id:vehicle.id,status:"to_schedule"});
 return NextResponse.json({ok:true,saleConcluded:true,orderNumber,invoiceNumber,vehicleId:vehicle.id,vin:vin||null,vehicleMatched:!!vin&&vehicle.internal_ref?.startsWith("AUTO-")===false,registrationStatus:"to_submit",message:"Vente enregistrée. Le véhicule est sorti du stock disponible et un dossier carte grise est prêt à déposer."});
}
