"use client";
import React,{useState}from"react";
import SeoGlobalTracker from "./SeoGlobalTracker";

const cityLinks=[
 ["Toulouse","toulouse"],["Paris","paris"],["Lyon","lyon"],["Marseille","marseille"],
 ["Bordeaux","bordeaux"],["Lille","lille"],["Nantes","nantes"],["Strasbourg","strasbourg"],
 ["Montpellier","montpellier"],["Nice","nice"],["Rennes","rennes"],["Grenoble","grenoble"],
];

export default function RootLayout({children}:{children:React.ReactNode}){
 const[open,setOpen]=useState(false);const close=()=>setOpen(false);
 return <html lang="fr"><body>
  <SeoGlobalTracker/>
  <header className="header"><div className="top"><a href="/" className="brand" onClick={close}><span className="icon">N</span><span><strong>NeoDrive</strong><small>Mobilité électrique accessible</small></span></a><div className="actions"><a className="whatsapp" href="https://wa.me/33628261446" target="_blank" rel="noreferrer">WhatsApp</a><button onClick={()=>setOpen(!open)}>{open?"✕":"☰"}</button></div></div><nav className={open?"menu open":"menu"}><a className="financeLink" href="/financement" onClick={close}>Financement</a><a href="/" onClick={close}>Accueil</a><a href="/produit" onClick={close}>Voitures</a><a className="cities" href="/voiture-sans-permis" onClick={close}>Villes</a><a className="pro" href="/professional" onClick={close}>NeoDrive Pro</a><a className="light" href="/light-mobility" onClick={close}>NeoDrive Deux Roues</a><a href="/videos" onClick={close}>Vidéos</a><a href="/livraison" onClick={close}>Livraison</a><a href="/sav" onClick={close}>SAV</a><a href="/pieces" onClick={close}>Pièces</a><a href="/faq" onClick={close}>FAQ</a><a href="/contact" onClick={close}>Contact</a></nav></header>
  {children}
  <footer className="seoFooter">
    <div className="footerInner">
      <div className="footerBrand"><strong>NeoDrive</strong><span>Voiture sans permis électrique · Livraison en France</span></div>
      <div><strong>Recherches utiles</strong><div className="footerLinks"><a href="/voiture-sans-permis">Voiture sans permis</a><a href="/voiture-sans-permis-electrique">Électrique</a><a href="/voiture-sans-permis-occasion">Occasion</a><a href="/prix-voiture-sans-permis">Prix</a><a href="/citroen-ami-ou-neodrive">Citroën Ami</a><a href="/fiat-topolino-ou-neodrive">Fiat Topolino</a><a href="/videos">Vidéos réelles</a></div></div>
      <div><strong>Voiture sans permis par ville</strong><div className="footerLinks">{cityLinks.map(([name,slug])=><a key={slug} href={`/voiture-sans-permis/${slug}`}>{name}</a>)}</div></div>
    </div>
  </footer>
  <style jsx global>{`html,body{margin:0;padding:0;width:100%;max-width:100%;overflow-x:clip;background:#fff;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}*{box-sizing:border-box}img,video,iframe,svg{max-width:100%}.trustBar{overflow:visible!important;background:transparent!important;box-shadow:none!important;gap:16px!important}.trustBar>div{position:relative;border:1px solid #ececec!important;border-right:1px solid #ececec!important;border-radius:22px;background:#fff;box-shadow:0 18px 45px rgba(0,0,0,.08);padding:24px 20px 24px 78px!important;text-align:left!important;min-height:108px;display:flex;flex-direction:column;justify-content:center}.trustBar>div:before{position:absolute;left:20px;top:50%;transform:translateY(-50%);width:44px;height:44px;border-radius:15px;display:grid;place-items:center;font-size:22px;background:linear-gradient(135deg,#fff3e8,#ffe8f1)}.trustBar>div:nth-child(1):before{content:"🏅"}.trustBar>div:nth-child(2):before{content:"📍"}.trustBar>div:nth-child(3):before{content:"🚚"}.trustBar strong{font-size:20px!important}.trustBar span{font-size:13px!important}@media(max-width:900px){.trustBar{grid-template-columns:1fr!important;gap:10px!important;margin-top:14px!important;margin-bottom:42px!important}.trustBar>div{min-height:80px;padding:16px 16px 16px 68px!important}.trustBar>div:before{left:15px;width:40px;height:40px}}`}</style>
  <style jsx>{`.header{position:sticky;top:0;z-index:9999;width:100%;background:rgba(255,255,255,.98);backdrop-filter:blur(18px);border-bottom:1px solid #eee;padding:10px 14px;box-shadow:0 8px 28px rgba(0,0,0,.05)}.top{display:flex;align-items:center;justify-content:space-between;gap:10px}.brand{display:flex;align-items:center;gap:10px;color:#111;text-decoration:none}.brand>span:last-child{min-width:0}.icon{width:38px;height:38px;flex:0 0 38px;border-radius:13px;background:linear-gradient(135deg,#ff7a00,#ff006e);color:white;display:grid;place-items:center;font-weight:950;font-size:23px}.brand strong{display:block;font-size:24px;line-height:1;font-weight:950;letter-spacing:-1px}.brand small{display:block;margin-top:3px;font-size:11px;color:#666;font-weight:700}.actions{display:flex;align-items:center;gap:8px}.whatsapp{background:#25d366;color:white;text-decoration:none;padding:10px 13px;border-radius:14px;font-size:14px;font-weight:900}.actions button{width:42px;height:42px;border:0;border-radius:14px;background:#111;color:white;font-size:22px}.menu{display:none;margin-top:12px;grid-template-columns:1fr 1fr;gap:8px}.menu.open{display:grid}.menu a{text-decoration:none;color:#111;background:#f5f5f5;padding:12px 9px;border-radius:14px;font-size:14px;font-weight:850;text-align:center}.menu .financeLink{background:#e9f5e5;color:#175d2a}.menu .cities{background:#fff0e7;color:#a9471f}.menu .pro{background:#173d23;color:white}.menu .light{background:#eaf7ff;color:#0874b9}.seoFooter{background:#101010;color:#fff;padding:42px 20px 50px;margin-top:20px}.footerInner{max-width:1180px;margin:auto;display:grid;grid-template-columns:1.1fr 1fr 1.4fr;gap:30px}.footerBrand{display:flex;flex-direction:column;gap:8px}.footerBrand strong{font-size:28px}.footerBrand span{color:#aaa;line-height:1.5}.footerLinks{display:flex;flex-wrap:wrap;gap:9px 13px;margin-top:13px}.footerLinks a{color:#ddd;text-decoration:none;font-size:13px}.footerLinks a:hover{text-decoration:underline}@media(min-width:900px){.header{padding:14px 32px}.top{max-width:1180px;margin:auto}.icon{width:44px;height:44px;flex-basis:44px}.brand strong{font-size:30px}.brand small{font-size:13px}.actions button{display:none}.menu,.menu.open{max-width:1320px;margin:14px auto 0;display:flex;justify-content:center;flex-wrap:wrap;gap:8px}.menu a{padding:10px 13px;border-radius:999px}.whatsapp{padding:12px 22px;font-size:16px}}@media(max-width:800px){.footerInner{grid-template-columns:1fr;gap:26px}}@media(max-width:390px){.brand small{max-width:115px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.whatsapp{padding:9px 10px;font-size:13px}}`}</style>
 </body></html>
}
