import { NextResponse } from "next/server";
import OpenAI from "openai";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const SUPABASE_URL = "https://tzlsdjzcxdjaatcpwqwn.supabase.co";
const sleep = (ms:number)=>new Promise(r=>setTimeout(r,ms));

type QueueItem={id:string;caption:string;media_url:string|null;content_type:string;hook:string|null;assetId?:string|null;generated?:boolean};
type Asset={id:string;public_url:string;media_type:string;title:string|null;context:string|null;times_used:number|null;last_used_at:string|null};
function headers(key:string){return {Authorization:`Bearer ${key}`,apikey:key};}
function parisSlot(){const p=Object.fromEntries(new Intl.DateTimeFormat("fr-FR",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()).map(x=>[x.type,x.value]));const h=Number(p.hour),m=Number(p.minute);if(h===9&&m>=20&&m<=55)return "morning";if(h===18&&m>=20&&m<=55)return "evening";return null;}

const THEMES=[
  {name:"prix",brief:"Angle prix et accessibilité. Expliquer qu'une voiture sans permis électrique neuve peut commencer à 3 990 €, sans dévaloriser le produit.",keywords:"voiture sans permis électrique, prix, 3 990 €, mobilité accessible"},
  {name:"look",brief:"Angle design/look. Montrer qu'un petit véhicule peut avoir une vraie présence et ne pas donner une impression de jouet.",keywords:"NeoDrive, design, look, voiture sans permis, compacte"},
  {name:"acier",brief:"Angle conception. Dire précisément que la conception fait largement appel à l'acier et parler d'impression de robustesse, sans faire de promesse de sécurité non démontrée.",keywords:"acier, conception, robuste, voiture sans permis électrique"},
  {name:"quotidien",brief:"Angle usage réel : travail, courses, déplacements de proximité, stationnement, simplicité.",keywords:"mobilité du quotidien, trajets courts, voiture sans permis, pratique"},
  {name:"electrique",brief:"Angle 100 % électrique : simplicité, silence, usage local. Ne pas inventer d'autonomie.",keywords:"100 % électrique, mobilité électrique, voiture sans permis"},
  {name:"recharge",brief:"Angle recharge : branchement sur prise 220 V et simplicité d'utilisation au quotidien.",keywords:"recharge 220 V, voiture électrique, NeoDrive"},
  {name:"2places",brief:"Angle format compact et deux places : petite dehors, utile dedans, facile à stationner.",keywords:"2 places, compacte, stationnement, voiture sans permis"},
  {name:"fiabilite",brief:"Angle fiabilité sans promesse absolue : insister sur conception simple, préparation, contrôles et suivi SAV.",keywords:"fiabilité, préparation, SAV, voiture sans permis électrique"},
  {name:"coulisses",brief:"Angle coulisses d'une vraie entreprise : préparation, livraison, stockage, essais, travail quotidien. Faire authentique, pas publicitaire.",keywords:"NeoDrive, livraison, préparation, coulisses"},
  {name:"accessible",brief:"Angle accessibilité de la mobilité : véhicule compact, conduite sans permis B selon la catégorie, déplacements de proximité. Ne pas présenter cela comme adapté à tout le monde.",keywords:"sans permis, mobilité accessible, voiture électrique, 45 km/h"},
];

function themeForNow(){const d=new Date();const n=Math.floor(d.getTime()/43200000);return THEMES[n%THEMES.length];}

async function selectQueue(force:boolean):Promise<QueueItem|null>{const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)return null;const u=new URL(`${SUPABASE_URL}/rest/v1/social_content_queue`);u.searchParams.set("platform","eq.instagram");u.searchParams.set("status","eq.scheduled");if(!force)u.searchParams.set("publish_at",`lte.${new Date().toISOString()}`);u.searchParams.set("select","id,caption,media_url,content_type,hook");u.searchParams.set("order","publish_at.asc");u.searchParams.set("limit","1");const r=await fetch(u,{headers:headers(key),cache:"no-store"});const j=await r.json();return r.ok&&Array.isArray(j)&&j[0]?j[0]:null;}

async function selectAsset():Promise<Asset|null>{const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)return null;const u=new URL(`${SUPABASE_URL}/rest/v1/social_media_assets`);u.searchParams.set("status","eq.ready");u.searchParams.set("select","id,public_url,media_type,title,context,times_used,last_used_at");u.searchParams.set("order","times_used.asc.nullsfirst,last_used_at.asc.nullsfirst,priority.desc,created_at.asc");u.searchParams.set("limit","1");const r=await fetch(u,{headers:headers(key),cache:"no-store"});const j=await r.json();return r.ok&&Array.isArray(j)&&j[0]?j[0]:null;}

async function generateCaption(asset:Asset){const theme=themeForNow();const fallback=`${theme.name==="prix"?"Une voiture sans permis électrique neuve à partir de 3 990 € : l'idée NeoDrive est de garder une mobilité simple et accessible.":theme.name==="acier"?"Une conception qui fait largement appel à l'acier, un format compact et un look volontairement sobre : NeoDrive cherche surtout à rester simple et pratique au quotidien.":theme.name==="look"?"Compacte, mais avec une vraie présence. NeoDrive mise sur un look de petite voiture, pas sur l'effet gadget.":"Une NeoDrive dans la vraie vie : un format compact, 100 % électrique et pensé pour les déplacements du quotidien."}\n\n#NeoDrive #VoitureSansPermis #MobiliteElectrique #VSP`;
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return {caption:fallback,hook:theme.name};
  try{
    const client=new OpenAI({apiKey});
    const facts="Faits autorisés : NeoDrive propose des voitures sans permis électriques 2 places, limitées à 45 km/h selon la catégorie, recharge sur prise 220 V, gamme à partir de 3 990 €. La conception fait largement appel à l'acier. Ne jamais inventer autonomie, sécurité, homologation, disponibilité, garantie, performance ou avis client.";
    const prompt=`Tu écris le prochain post Instagram de NeoDrive en français. Objectif : crédibilité, recherche Instagram et potentiel d'engagement, pas un texte qui sonne IA. ${facts}\nThème : ${theme.brief}\nMots-clés à intégrer naturellement si pertinents : ${theme.keywords}.\nMédia : ${asset.media_type}. Nom : ${asset.title||"non renseigné"}. Contexte réel donné par l'entreprise : ${asset.context||"aucun"}.\nRègles : 2 à 4 phrases courtes; première phrase = hook concret; ton propriétaire de petite entreprise; aucun superlatif vide; 0 à 2 emojis maximum; 4 à 6 hashtags ciblés; ne pas dire 'Découvrez'; ne pas prétendre avoir vu un détail absent du contexte. Retourne uniquement la légende finale.`;
    const content:any[]=[{type:"input_text",text:prompt}];
    if(asset.media_type!=="reel"&&asset.public_url)content.push({type:"input_image",image_url:asset.public_url});
    const response=await client.responses.create({model:process.env.OPENAI_SOCIAL_MODEL||"gpt-4.1-mini",input:[{role:"user",content}] as any,max_output_tokens:300});
    const text=(response.output_text||"").trim();
    return {caption:text||fallback,hook:theme.name};
  }catch{return {caption:fallback,hook:theme.name};}
}

async function generatedItem():Promise<QueueItem|null>{const asset=await selectAsset();if(!asset)return null;const g=await generateCaption(asset);return {id:`asset:${asset.id}`,caption:g.caption,media_url:asset.public_url,content_type:asset.media_type==="reel"?"reel":"post",hook:g.hook,assetId:asset.id,generated:true};}

async function updateQueue(id:string,status:string,extra:Record<string,unknown>={}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key||id.startsWith("asset:"))return;await fetch(`${SUPABASE_URL}/rest/v1/social_content_queue?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers(key),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({status,updated_at:new Date().toISOString(),...extra}),cache:"no-store"});}

async function markAsset(id:string|undefined,success:boolean){if(!id)return;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)return;const current=await fetch(`${SUPABASE_URL}/rest/v1/social_media_assets?id=eq.${encodeURIComponent(id)}&select=times_used`,{headers:headers(key),cache:"no-store"});const rows=await current.json().catch(()=>[]);const used=Array.isArray(rows)&&rows[0]?.times_used?Number(rows[0].times_used):0;await fetch(`${SUPABASE_URL}/rest/v1/social_media_assets?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers(key),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(success?{times_used:used+1,last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}:{updated_at:new Date().toISOString()}),cache:"no-store"});}

async function account(token:string){const u=new URL("https://graph.instagram.com/me");u.searchParams.set("fields","id,username");u.searchParams.set("access_token",token);const r=await fetch(u,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.id)throw new Error(j?.error?.message||"Instagram account error");return j;}
async function wait(id:string,token:string){for(let i=0;i<15;i++){const u=new URL(`https://graph.instagram.com/${id}`);u.searchParams.set("fields","status_code,status");u.searchParams.set("access_token",token);const r=await fetch(u,{cache:"no-store"});const j=await r.json();if(j.status_code==="FINISHED")return;if(j.status_code==="ERROR"||j.status_code==="EXPIRED")throw new Error(`Media processing failed: ${JSON.stringify(j)}`);await sleep(2000);}throw new Error("Media processing timeout");}
async function publish(accountId:string,token:string,item:QueueItem){if(!item.media_url)throw new Error("Missing media URL");const u=new URL(`https://graph.instagram.com/${accountId}/media`);const isVideo=item.content_type==="reel"||item.content_type==="video";const params:Record<string,string>={caption:item.caption,access_token:token};if(isVideo){params.media_type="REELS";params.video_url=item.media_url;params.share_to_feed="true";}else params.image_url=item.media_url;const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params),cache:"no-store"});const j=await r.json();if(!r.ok||!j.id)throw new Error(j?.error?.message||"Container creation failed");await wait(j.id,token);await sleep(4000);for(let i=0;i<5;i++){const pu=new URL(`https://graph.instagram.com/${accountId}/media_publish`);const pr=await fetch(pu,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({creation_id:j.id,access_token:token}),cache:"no-store"});const pj=await pr.json();if(pr.ok&&pj.id)return pj.id;if(!String(pj?.error?.message||"").toLowerCase().includes("media id is not available"))throw new Error(pj?.error?.message||"Publish failed");await sleep(3000);}throw new Error("Instagram publish failed");}

export async function GET(request:Request){const url=new URL(request.url);const force=url.searchParams.get("force")==="1";const secret=process.env.CRON_SECRET;const alt=process.env.INSTAGRAM_AUTOMATION_SECRET;const auth=request.headers.get("authorization");if(!((secret&&auth===`Bearer ${secret}`)||(alt&&auth===`Bearer ${alt}`)))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});if(!force&&!parisSlot())return NextResponse.json({ok:true,skipped:true,reason:"Outside Paris publishing window"});const token=process.env.INSTAGRAM_ACCESS_TOKEN;if(!token)return NextResponse.json({ok:false,error:"INSTAGRAM_ACCESS_TOKEN missing"},{status:503});let queued=await selectQueue(force);if(!queued)queued=await generatedItem();if(!queued)return NextResponse.json({ok:true,skipped:true,reason:"No scheduled post and no ready media asset"});try{await updateQueue(queued.id,"publishing");const a=await account(token);const mediaId=await publish(a.id,token,queued);await updateQueue(queued.id,"published",{external_post_id:mediaId,error_message:null});await markAsset(queued.assetId,true);return NextResponse.json({ok:true,published:true,source:queued.generated?"generated-media-library":"queue",queueId:queued.id,account:a.username||null,mediaId,media:queued.media_url,mediaType:queued.content_type,theme:queued.hook,forced:force});}catch(e){await updateQueue(queued.id,"failed",{error_message:e instanceof Error?e.message:"Unknown error"});await markAsset(queued.assetId,false);return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Unknown error"},{status:500});}}
