import { NextResponse } from "next/server";
import OpenAI from "openai";
export const dynamic="force-dynamic";export const maxDuration=60;
const SB="https://tzlsdjzcxdjaatcpwqwn.supabase.co",sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
type Q={id:string;caption:string;media_url:string;content_type:string;hook:string|null;retry_count:number|null;max_retries:number|null};type A={id:string;public_url:string;media_type:string;title:string|null;context:string|null;times_used:number|null};
const H=(k:string)=>({Authorization:`Bearer ${k}`,apikey:k});const video=(t:string,u:string)=>/video|reel/i.test(t||"")||/\.(mp4|mov|m4v)(\?|$)/i.test(u||"");
async function queue(k:string){const u=new URL(`${SB}/rest/v1/social_content_queue`);u.searchParams.set("platform","eq.instagram");u.searchParams.set("status","eq.scheduled");u.searchParams.set("publish_at",`lte.${new Date().toISOString()}`);u.searchParams.set("select","id,caption,media_url,content_type,hook,retry_count,max_retries");u.searchParams.set("order","publish_at.asc");u.searchParams.set("limit","1");const r=await fetch(u,{headers:H(k),cache:"no-store"});const j=await r.json();return r.ok&&j?.[0]?j[0] as Q:null;}
async function asset(k:string){const r=await fetch(`${SB}/rest/v1/social_media_assets?status=eq.ready&select=id,public_url,media_type,title,context,times_used&order=priority.desc,ai_quality_score.desc.nullslast,times_used.asc.nullsfirst,last_used_at.asc.nullsfirst&limit=40`,{headers:H(k),cache:"no-store"});const j=await r.json();if(!r.ok||!Array.isArray(j))return null;return j.find((a:A)=>video(a.media_type,a.public_url)||/\.jpe?g(\?|$)/i.test(a.public_url))||null;}
async function caption(a:A){const fallback=`Une NeoDrive dans la vraie vie : compacte, électrique et pensée pour les déplacements du quotidien.\n\nÀ partir de 3 990 € TTC. Recharge sur prise 220 V.\n\n#NeoDrive #VoitureSansPermis #VSP #MobiliteElectrique`;if(!process.env.OPENAI_API_KEY)return fallback;try{const c=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await c.responses.create({model:process.env.OPENAI_SOCIAL_MODEL||"gpt-4.1-mini",input:`Légende Instagram NeoDrive naturelle à partir d'un vrai média. Contexte:${a.context||"aucun"}. Faits sûrs: voiture sans permis électrique 2 places, à partir de 3 990 € TTC, recharge 220 V. Varie prix, look, usage, coulisses, livraison, recharge, SAV. 2-4 phrases, hook concret, 4-6 hashtags. N'invente autonomie, sécurité, stock, garantie, avis ou droit de conduire. Retourne seulement la légende.`,max_output_tokens:260});return r.output_text.trim()||fallback;}catch{return fallback;}}
async function patch(k:string,id:string,data:any){await fetch(`${SB}/rest/v1/social_content_queue?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...H(k),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({...data,updated_at:new Date().toISOString()}),cache:"no-store"});}
async function mark(k:string,id:string){const r=await fetch(`${SB}/rest/v1/social_media_assets?id=eq.${id}&select=times_used`,{headers:H(k)});const x=(await r.json().catch(()=>[]))?.[0];await fetch(`${SB}/rest/v1/social_media_assets?id=eq.${id}`,{method:"PATCH",headers:{...H(k),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({times_used:Number(x?.times_used||0)+1,last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()})});}
async function acct(t:string){const u=new URL("https://graph.instagram.com/me");u.searchParams.set("fields","id,username");u.searchParams.set("access_token",t);const r=await fetch(u);const j=await r.json();if(!r.ok||!j.id)throw new Error(j?.error?.message||"Instagram account error");return j;}
async function wait(id:string,t:string){for(let i=0;i<18;i++){const u=new URL(`https://graph.instagram.com/${id}`);u.searchParams.set("fields","status_code,status");u.searchParams.set("access_token",t);const r=await fetch(u);const j=await r.json();if(j.status_code==="FINISHED")return;if(["ERROR","EXPIRED"].includes(j.status_code))throw new Error(j?.status||"Media processing failed");await sleep(2000);}throw new Error("Media processing timeout");}
async function publish(aid:string,t:string,url:string,msg:string,isV:boolean){const u=new URL(`https://graph.instagram.com/${aid}/media`);const p:Record<string,string>={caption:msg,access_token:t};if(isV){p.media_type="REELS";p.video_url=url;p.share_to_feed="true";}else p.image_url=url;const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(p)});const j=await r.json();if(!r.ok||!j.id)throw new Error(j?.error?.message||"Container creation failed");await wait(j.id,t);for(let i=0;i<6;i++){const pu=new URL(`https://graph.instagram.com/${aid}/media_publish`);const pr=await fetch(pu,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({creation_id:j.id,access_token:t})});const pj=await pr.json();if(pr.ok&&pj.id)return pj.id;await sleep(2500);}throw new Error("Instagram publish failed");}
export async function GET(req:Request){const s=process.env.CRON_SECRET,alt=process.env.INSTAGRAM_AUTOMATION_SECRET,auth=req.headers.get("authorization");if(!((s&&auth===`Bearer ${s}`)||(alt&&auth===`Bearer ${alt}`)))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const k=process.env.SUPABASE_SERVICE_ROLE_KEY,t=process.env.INSTAGRAM_ACCESS_TOKEN;if(!k||!t)return NextResponse.json({ok:false,error:"Configuration missing"},{status:503});let q=await queue(k),a:A|null=null,msg="",url="",typ="";if(q){msg=q.caption;url=q.media_url;typ=q.content_type;await patch(k,q.id,{status:"publishing",last_attempt_at:new Date().toISOString()});}else{a=await asset(k);if(!a)return NextResponse.json({ok:true,skipped:true,reason:"No due queue or compatible media"});msg=await caption(a);url=a.public_url;typ=a.media_type;}try{const ac=await acct(t);const id=await publish(ac.id,t,url,msg,video(typ,url));if(q)await patch(k,q.id,{status:"published",external_post_id:id,error_message:null});if(a)await mark(k,a.id);return NextResponse.json({ok:true,published:true,source:q?"planned-queue":"fallback",mediaId:id,media:url,type:typ});}catch(e){if(q){const n=Number(q.retry_count||0)+1,max=Number(q.max_retries||3);await patch(k,q.id,{status:n>=max?"failed":"scheduled",retry_count:n,last_attempt_at:new Date().toISOString(),...(n>=max?{}:{publish_at:new Date(Date.now()+3600000).toISOString()}),error_message:e instanceof Error?e.message:"Unknown"});}return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Unknown"},{status:500});}}
