"use client";
import {useState} from "react";

type D={summary?:any;vehicles?:any[];orders?:any[];containers?:any[];imports?:any[]};
export default function ERP(){const[passcode,setPasscode]=useState("");const[data,setData]=useState<D>({});const[msg,setMsg]=useState("");const[loading,setLoading]=useState(false);const[file,setFile]=useState<File|null>(null);
async function load(){setLoading(true);setMsg("Chargement…");try{const r=await fetch('/api/erp/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Erreur');setData(j);setMsg('✅ Données à jour');}catch(e){setMsg(`❌ ${e instanceof Error?e.message:'Erreur'}`)}finally{setLoading(false)}}
async function packing(e:React.FormEvent){e.preventDefault();if(!file)return;setLoading(true);setMsg('Analyse IA de la packing list…');try{const fd=new FormData();fd.append('passcode',passcode);fd.append('file',file);const r=await fetch('/api/erp/import-packing-list',{method:'POST',body:fd});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Import impossible');setMsg(`✅ Packing list importée : ${j.detected} véhicule(s), ${j.created} créé(s), ${j.updated} mis à jour.`);await load();}catch(e){setMsg(`❌ ${e instanceof Error?e.message:'Erreur'}`)}finally{setLoading(false)}}
const s=data.summary||{};return <main style={{maxWidth:1200,margin:'0 auto',padding:'28px 18px 70px',fontFamily:'Arial,sans-serif'}}><h1>NeoDrive Control Tower</h1><p>Stock, conteneurs, ventes, paiements et carte grise dans un seul écran.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',margin:'18px 0'}}><input type="password" placeholder="Code interne" value={passcode} onChange={e=>setPasscode(e.target.value)} style={input}/><button onClick={load} disabled={loading} style={btn}>Actualiser</button></div>
<form onSubmit={packing} style={box}><h2>Importer une packing list</h2><p>PDF, image ou document exporté de l'usine. L'IA extrait les VIN et crée/met à jour automatiquement le stock.</p><input type="file" accept=".pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||loading} style={{...btn,marginLeft:12}}>Importer</button></form>{msg&&<p style={{fontWeight:700}}>{msg}</p>}
{s.vehicles!=null&&<><div style={grid}>{[['Véhicules',s.vehicles],['Disponibles',s.available],['Conteneurs',s.containers],['Commandes',s.orders],['CA commandes',eur(s.sales)],['À encaisser',eur(s.receivable)],['Valeur stock',eur(s.stockValue)]].map(([a,b])=><div style={card} key={String(a)}><div style={{fontSize:13,color:'#666'}}>{a}</div><div style={{fontSize:28,fontWeight:900}}>{String(b)}</div></div>)}</div><h2>État du parc</h2><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:25}}>{Object.entries(s.byStatus||{}).map(([k,v])=><span key={k} style={pill}>{k}: {String(v)}</span>)}</div>
<h2>Derniers véhicules</h2><div style={{overflowX:'auto'}}><table style={table}><thead><tr><th>Réf.</th><th>VIN</th><th>Version</th><th>Couleur</th><th>Statut</th><th>Emplacement</th></tr></thead><tbody>{(data.vehicles||[]).slice(0,80).map(v=><tr key={v.id}><td>{v.internal_ref}</td><td>{v.vin||'—'}</td><td>{v.version||v.model||'—'}</td><td>{v.color||'—'}</td><td><b>{v.status}</b></td><td>{v.location_label||'—'}</td></tr>)}</tbody></table></div>
<h2 style={{marginTop:36}}>Ventes / Carte grise</h2><div style={{overflowX:'auto'}}><table style={table}><thead><tr><th>Commande</th><th>Client</th><th>VIN</th><th>Total</th><th>Reste</th><th>Vente</th><th>Carte grise</th><th></th></tr></thead><tbody>{(data.orders||[]).map((o:any)=><tr key={o.id}><td><b>{o.order_number}</b></td><td>{o.customers?`${o.customers.first_name||''} ${o.customers.last_name||''}`:'—'}</td><td>{o.vehicles?.vin||'—'}</td><td>{eur(o.total_ttc)}</td><td>{eur(o.balance_due)}</td><td>{o.order_status}</td><td>{o.registration_status}</td><td><a href={`/erp/order/${o.id}`} style={{fontWeight:800}}>Ouvrir →</a></td></tr>)}</tbody></table></div>
<h2 style={{marginTop:36}}>Conteneurs</h2><div style={grid}>{(data.containers||[]).map((c:any)=><div style={card} key={c.id}><b>{c.container_number}</b><div>{c.status}</div><div>ETA : {c.eta||'—'}</div><div>{c.port_arrival||''}</div></div>)}</div></>}</main>}
function eur(n:any){return `${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:0})} €`}
const input:React.CSSProperties={padding:12,border:'1px solid #ccc',borderRadius:10,fontSize:16};const btn:React.CSSProperties={padding:'12px 18px',border:0,borderRadius:10,background:'#111',color:'#fff',fontWeight:800,cursor:'pointer'};const box:React.CSSProperties={padding:18,border:'1px solid #ddd',borderRadius:14,margin:'18px 0',background:'#fafafa'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,margin:'20px 0'};const card:React.CSSProperties={padding:16,border:'1px solid #e2e2e2',borderRadius:14,background:'#fff'};const pill:React.CSSProperties={padding:'8px 11px',background:'#f1f1f1',borderRadius:999,fontSize:13};const table:React.CSSProperties={width:'100%',borderCollapse:'collapse',fontSize:14};
