import { NextResponse } from "next/server";
import OpenAI from "openai";
export const dynamic="force-dynamic";export const maxDuration=60;
const SB="https://tzlsdjzcxdjaatcpwqwn.supabase.co";
type Asset={id:string;public_url:string;media_type:string;title:string|null;context:string|null;times_used:number|null};type Q={id:string;caption:string;media_url:string;content_type:string;retry_count:number|null;max_retries:number|null};
const H=(k:string)=>({Authorization:`Bearer ${k}`,apikey:k});const video=(t:string,u:string)=>/video|reel/i.test(t||"")||/\.(mp4|mov|m4v)(\?|$)/i.test(u||"");
async function getQueue(k:string){const u=new URL(`${SB}/rest/v1/social_content_queue`);u.searchParams.set("platform","eq.facebook");u.searchParams.set("status","eq.scheduled");u.searchParams.set("publish_at",`lte.${new Date().toISOString()}`);u.searchParams.set("select","id,caption,media_url,content_type,retry_count,max_retries");u.searchParams.set("order","publish_at.asc");u.searchParams.set("limit","1");const r=await fetch(u,{headers:H(k),cache:"no-store"});const j=await r.json();return r.ok&&j?.[0]?j[0] as Q:null;}
async function getAsset(k:string){const r=await fetch(`${SB}/rest/v1/social_media_assets?status=eq.ready&select=id,public_url,media_type,title,context,times_used&order=times_used.asc.nullsfirst,last_used_at.asc.nullsfirst&limit=1`,{headers:H(k),cache:"no-store"});const j=await r.json();return r.ok&&j?.[0]?j[0] as Asset:null;}
async function caption(a:Asset){const fb=`Une NeoDrive dans la vraie vie : compacte, électrique et pensée pour les déplacements du quotidien.\n\nÀ partir de 3 990 € TTC. Recharge sur prise 220 V.\n\n#NeoDrive #VoitureSansPermis #VSP #MobiliteElectrique`;if(!process.env.OPENAI_API_KEY)return fb;try{const c=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await c.responses.create({model:process.env.OPENAI_SOCIAL_MODEL||"gpt-4.1-mini",input:`Publication Facebook NeoDrive naturelle. Contexte réel: ${a.context||"aucun"}. Faits sûrs: VSP électrique 2 places, à partir de 3 990 € TTC, recharge 220 V. Choisis un angle parmi prix, look, usage, recharge, coulisses, livraison, préparation, SAV. 3-6 phrases, 2-5 hashtags, CTA discret. N'invente autonomie, sécurité, stock, garantie ou droit de conduire.`,max_output_tokens:280});return r.output_text.trim()||fb;}catch{return fb;}}
async function patch(k:string,id:string,data:any){await fetch(`${SB}/rest/v1/social_content_queue?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...H(k),"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({...data,updated_at:new Date().toISOString()}),cache:"no-store"});}
async function pageToken(t:string,p:string){const me=new URL("https://graph.facebook.com/v26.0/me");me.searchParams.set("fields","id");me.searchParams.set("access_token",t);const mr=await fetch(me);const mj=await mr.json();if(mr.ok&&String(mj.id)===p)return t;const a=new URL("https://graph.facebook.com/v26.0/me/accounts");a.searchParams.set("fields","id,access_token");a.searchParams.set("access_token",t);const ar=await fetch(a);const aj=await ar.json();const row=aj?.data?.find((x:any)=>String(x.id)===p);if(row?.access_token)return row.access_token;const e=aj?.error||mj?.error||{};if(Number(e.code)===190)throw new Error("Connexion Facebook expirée. Reconnecte Meta puis remplace FACEBOOK_PAGE_ACCESS_TOKEN dans Vercel.");throw new Error(e.message||"Facebook Page token invalide");}
async function publish(p:string,t:string,u:string,msg:string,v:boolean){const ep=`https://graph.facebook.com/v26.0/${p}/${v?"videos":"photos"}`;const b=v?new URLSearchParams({file_url:u,description:msg,access_token:t}):new URLSearchParams({url:u,caption:msg,published:"true",access_token:t});const r=await fetch(ep,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b});const j=await r.json();if(!r.ok||(!j.id&&!j.post_id)){const e=j?.error||{};throw new Error(`${e.message||"Facebook publish failed"}${e.code?` (code ${e.code})`:""}`);}return j.post_id||j.id;}
export async function GET(req:Request){const s=process.env.CRON_SECRET;if(!s||req.headers.get("authorization")!==`Bearer ${s}`)return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const k=process.env.SUPABASE_SERVICE_ROLE_KEY,t=process.env.FACEBOOK_PAGE_ACCESS_TOKEN,p=process.env.FACEBOOK_PAGE_ID;if(!k||!t||!p)return NextResponse.json({ok:false,error:"Configuration missing"},{status:503});let q=await getQueue(k);let a:Asset|null=null;let msg="",url="",typ="";if(q){msg=q.caption;url=q.media_url;typ=q.content_type;await patch(k,q.id,{status:"publishing",last_attempt_at:new Date().toISOString()});}else{a=await getAsset(k);if(!a)return NextResponse.json({ok:true,skipped:true,reason:"No due queue or media"});msg=await caption(a);url=a.public_url;typ=a.media_type;}try{const pt=await pageToken(t,p);const id=await publish(p,pt,url,msg,video(typ,url));if(q)await patch(k,q.id,{status:"published",external_post_id:id,error_message:null});return NextResponse.json({ok:true,published:true,source:q?"planned-queue":"fallback",postId:id,media:url});}catch(e){if(q){const n=Number(q.retry_count||0)+1,max=Number(q.max_retries||3);await patch(k,q.id,{status:n>=max?"failed":"scheduled",retry_count:n,last_attempt_at:new Date().toISOString(),publish_at:n>=max?undefined:new Date(Date.now()+60*60*1000).toISOString(),error_message:e instanceof Error?e.message:"Unknown"});}return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Unknown"},{status:500});}}
