import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import OpenAI from "openai";
export const dynamic="force-dynamic";export const maxDuration=60;const SB="https://tzlsdjzcxdjaatcpwqwn.supabase.co";
function safe(s:string){return s.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)}
async function upload(sb:any,file:File){const path=`packing-lists/${Date.now()}-${safe(file.name)}`;const {error}=await sb.storage.from("erp-documents").upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type||"application/octet-stream",upsert:false});if(error)throw error;return path;}
export async function POST(req:Request){const fd=await req.formData();const secret=process.env.CRON_SECRET;if(!secret||String(fd.get("passcode")||"")!==secret)return NextResponse.json({ok:false,error:"Code incorrect"},{status:401});const sk=process.env.SUPABASE_SERVICE_ROLE_KEY,oa=process.env.OPENAI_API_KEY;if(!sk||!oa)return NextResponse.json({ok:false,error:"Configuration incomplète"},{status:503});const file=fd.get("file");if(!(file instanceof File)||!file.size)return NextResponse.json({ok:false,error:"Packing list manquante"},{status:400});const sb=createClient(SB,sk,{auth:{persistSession:false}});const path=await upload(sb,file);const {data:imp,error:ie}=await sb.from("packing_imports").insert({filename:file.name,file_url:path,status:"processing"}).select().single();if(ie)return NextResponse.json({ok:false,error:ie.message},{status:500});try{const client=new OpenAI({apiKey:oa});const b64=Buffer.from(await file.arrayBuffer()).toString("base64");const r=await client.responses.create({model:process.env.OPENAI_DOCUMENT_MODEL||"gpt-5-mini",input:[{role:"user",content:[{type:"input_text",text:"Analyse cette packing list de véhicules. Retourne UNIQUEMENT un JSON valide: {container_number, bl_number, supplier_order_number, supplier_name, eta, vehicles:[{vin,chassis_number,model,version,color,battery_type,motor_serial,controller_serial,factory_cost,currency}]}. Une entrée par véhicule. Recopie les VIN/châssis exactement. null si absent. N'invente rien."},{type:"input_file",filename:file.name,file_data:`data:${file.type||"application/pdf"};base64,${b64}`}]}] as any,max_output_tokens:5000});const txt=(r.output_text||"").trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();const j=JSON.parse(txt);let supplierOrderId:any=null;if(j.supplier_order_number){const {data:existing}=await sb.from("supplier_orders").select("id").eq("order_number",j.supplier_order_number).maybeSingle();if(existing)supplierOrderId=existing.id;else{const {data}=await sb.from("supplier_orders").insert({order_number:j.supplier_order_number,supplier_name:j.supplier_name||null,status:"ordered",ordered_at:new Date().toISOString()}).select().single();supplierOrderId=data?.id||null;}}
let containerId:any=null;if(j.container_number){const {data:existing}=await sb.from("containers").select("id").eq("container_number",j.container_number).maybeSingle();if(existing)containerId=existing.id;else{const {data}=await sb.from("containers").insert({container_number:j.container_number,supplier_order_id:supplierOrderId,bl_number:j.bl_number||null,status:"in_transit",eta:j.eta||null,port_arrival:"Le Havre"}).select().single();containerId=data?.id||null;}}
let imported=0,updated=0;for(const [i,v] of (Array.isArray(j.vehicles)?j.vehicles:[]).entries()){const vin=String(v.vin||v.chassis_number||"").replace(/\s+/g,"").toUpperCase();if(!vin)continue;const {data:existing}=await sb.from("vehicles").select("id,status,current_customer_id").or(`vin.eq.${vin},chassis_number.eq.${vin}`).maybeSingle();const payload={vin,chassis_number:v.chassis_number||vin,model:v.model||null,version:v.version||null,color:v.color||null,battery_type:v.battery_type||null,motor_serial:v.motor_serial||null,controller_serial:v.controller_serial||null,supplier_order_id:supplierOrderId,container_id:containerId,factory_cost:Number(v.factory_cost)||null,updated_at:new Date().toISOString()};if(existing){await sb.from("vehicles").update({...payload,status:existing.status==="sold"?"sold":"in_transit"}).eq("id",existing.id);updated++;}else{await sb.from("vehicles").insert({...payload,internal_ref:`ND-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}-${String(i+1).padStart(2,"0")}`,status:"in_transit"});imported++;}}
await sb.from("packing_imports").update({container_number:j.container_number||null,supplier_order_number:j.supplier_order_number||null,status:"completed",rows_detected:Array.isArray(j.vehicles)?j.vehicles.length:0,rows_imported:imported+updated,ai_extracted:j,completed_at:new Date().toISOString()}).eq("id",imp.id);return NextResponse.json({ok:true,importId:imp.id,container:j.container_number||null,detected:Array.isArray(j.vehicles)?j.vehicles.length:0,created:imported,updated});}catch(e){await sb.from("packing_imports").update({status:"failed",error_message:e instanceof Error?e.message:"Import failed",completed_at:new Date().toISOString()}).eq("id",imp.id);return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Import failed"},{status:500});}}
