import Image from "next/image";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { commercialPages,commercialPageBySlug } from "../../../lib/seo-commercial";

const site="https://www.easydrive-auto.fr";

export function generateStaticParams(){return commercialPages.map(page=>({slug:page.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=commercialPageBySlug(slug);return page?{title:`${page.title} | NeoDrive`,description:page.description,alternates:{canonical:`${site}/offres/${slug}`},openGraph:{title:page.title,description:page.description,url:`${site}/offres/${slug}`,images:[`${site}/hero.png`]}}:{};}

export default async function CommercialPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const page=commercialPageBySlug(slug);if(!page)notFound();
 const schema={"@context":"https://schema.org","@graph":[{"@type":"WebPage",name:page.title,description:page.description,url:`${site}/offres/${page.slug}`,publisher:{"@type":"Organization",name:"NeoDrive",url:site}},{"@type":"FAQPage",mainEntity:page.questions.map(q=>({"@type":"Question",name:q.question,acceptedAnswer:{"@type":"Answer",text:q.answer}}))}]};
 return <main style={{fontFamily:"Arial,sans-serif",color:"#111"}}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><section style={{maxWidth:1120,margin:"0 auto",padding:"75px 22px 45px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:42,alignItems:"center"}}><div><span style={{fontSize:13,fontWeight:900,letterSpacing:1.5,color:"#ff5a1f"}}>{page.eyebrow}</span><h1 style={{fontSize:"clamp(38px,6vw,67px)",lineHeight:1.02,letterSpacing:-2,margin:"16px 0"}}>{page.title}</h1><p style={{fontSize:18,lineHeight:1.7,color:"#525861"}}>{page.intro}</p><a href="https://wa.me/33628261446" style={{display:"inline-block",padding:"15px 22px",borderRadius:13,background:"#111",color:"white",textDecoration:"none",fontWeight:800}}>Recevoir les photos et le prix</a></div><Image src="/hero.png" alt="NeoDrive voiture sans permis électrique deux places" width={680} height={540} style={{width:"100%",height:"auto",borderRadius:24}} priority/></section><section style={{background:"#f7f7f7",padding:"58px 22px"}}><div style={{maxWidth:1050,margin:"0 auto"}}><h2>Les points à vérifier pour votre projet</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:15}}>{page.benefits.map(item=><article key={item} style={{padding:20,borderRadius:16,background:"white",lineHeight:1.6}}><strong>{item}</strong></article>)}</div></div></section><section style={{maxWidth:1000,margin:"0 auto",padding:"60px 22px"}}><h2>Questions fréquentes</h2>{page.questions.map(item=><article key={item.question} style={{padding:"16px 0",borderBottom:"1px solid #eee"}}><h3>{item.question}</h3><p style={{lineHeight:1.7,color:"#555"}}>{item.answer}</p></article>)}</section><section style={{maxWidth:1000,margin:"0 auto",padding:"0 22px 65px"}}><h2>Pour aller plus loin</h2><ul style={{lineHeight:2}}>{page.related.map(slug=>{const related=commercialPageBySlug(slug);return related?<li key={slug}><a href={`/offres/${slug}`}>{related.title}</a></li>:null})}<li><a href="/blog">Tous les guides NeoDrive</a></li><li><a href="/produit">Découvrir la gamme NeoDrive</a></li></ul><a href="https://wa.me/33628261446" style={{display:"inline-block",padding:"15px 22px",borderRadius:13,background:"#ff5a1f",color:"white",textDecoration:"none",fontWeight:800}}>Parler de mon projet sur WhatsApp</a></section></main>
}
