"use client";
import{useState}from"react";import styles from"./produit.module.css";
const RAW="https://raw.githubusercontent.com/khelifamansour/neodrive-site/main/public/neodrive-switch";
const photos=[
 [RAW+"/gallery/showroom.svg","En concession","NeoDrive SWITCH photographiée en concession"],
 [RAW+"/real/exterieur-avant.webp","Extérieur","Vue avant de la NeoDrive SWITCH"],
 [RAW+"/real/exterieur-ville.webp","En situation","NeoDrive SWITCH en environnement urbain"],
 [RAW+"/real/exterieur-arriere.webp","Extérieur","Vue arrière de la NeoDrive SWITCH"],
 [RAW+"/gallery/interieur.svg","Intérieur","Habitacle réel et tableau de bord NeoDrive SWITCH"],
 [RAW+"/real/devant-atelier.webp","Préparation","NeoDrive SWITCH devant notre atelier"],
 [RAW+"/real/stock-couleurs.webp","Stock réel","Plusieurs NeoDrive SWITCH disponibles"],
 [RAW+"/real/livraison-transporteur.webp","Livraison","Transport et livraison des voitures NeoDrive"]
];
const specs=[["Moteur","3 kW électrique"],["Vitesse","45 km/h"],["Autonomie indicative","50 à 70 km"],["Recharge","220 V · env. 6 h"],["Places","2"],["Dimensions","2,50 × 1,30 × 1,65 m"]];
export default function Produit(){const[index,setIndex]=useState(0);const[zoom,setZoom]=useState(false);const move=(d:number)=>setIndex((index+d+photos.length)%photos.length);return <main className={styles.page}>
<section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>VOITURE SANS PERMIS · 100 % ÉLECTRIQUE</span><h1>NeoDrive<br/><em>SWITCH</em></h1><p>Une voiture électrique deux places, compacte et simple à utiliser. Ici, pas d’image de synthèse : découvrez le véhicule réel, son habitacle, sa préparation et sa livraison.</p><div className={styles.price}><span>À partir de</span><strong>3 990 € TTC</strong></div><div className={styles.actions}><a href="https://wa.me/33628261446?text=Bonjour%2C%20je%20souhaite%20recevoir%20une%20vid%C3%A9o%20de%20la%20NeoDrive%20SWITCH" target="_blank" rel="noreferrer">Recevoir une vidéo</a><a className={styles.secondary} href="#galerie">Voir les photos</a></div><small>Prix selon version, équipement et disponibilité.</small></div><div className={styles.heroPhoto}><img src={photos[0][0]} alt={photos[0][2]}/><div className={styles.heroBadge}>PHOTO RÉELLE · VÉHICULE NEODRIVE</div><div className={styles.heroFacts}><b>2 places</b><b>45 km/h</b><b>Recharge 220 V</b></div></div></section>
<section className={styles.reassurance}><article><span>01</span><b>Véhicule neuf</b><small>Préparé et contrôlé avant livraison</small></article><article><span>02</span><b>Photos réelles</b><small>Vous voyez le véhicule que nous distribuons</small></article><article><span>03</span><b>Paiement à la livraison</b><small>Après réception et contrôle</small></article><article><span>04</span><b>Livraison en France</b><small>Organisation directement par NeoDrive</small></article></section>
<section id="galerie" className={styles.gallerySection}><div className={styles.heading}><span className={styles.eyebrow}>LE VÉHICULE RÉEL</span><h2>Voyez la voiture avant de l’acheter.</h2><p>Extérieur, intérieur, stock, préparation et livraison. Faites défiler les photos de gauche à droite sur téléphone.</p></div><div className={styles.viewer}><div className={styles.stage}><img src={photos[index][0]} alt={photos[index][2]} onClick={()=>setZoom(true)}/><div className={styles.caption}><span>{photos[index][1]}</span><b>{photos[index][2]}</b></div><button aria-label="Photo précédente" className={styles.prev} onClick={()=>move(-1)}>‹</button><button aria-label="Photo suivante" className={styles.next} onClick={()=>move(1)}>›</button><span className={styles.counter}>{index+1} / {photos.length}</span></div><div className={styles.thumbs}>{photos.map(([src,label,alt],i)=><button key={src} className={i===index?styles.active:""} onClick={()=>setIndex(i)}><img src={src} alt={alt}/><span>{label}</span></button>)}</div></div></section>
<section className={styles.realLife}><div className={styles.realLifeCopy}><span className={styles.eyebrow}>PAS UNE PHOTO DE CATALOGUE</span><h2>Des voitures que nous préparons vraiment.</h2><p>NeoDrive montre aussi les véhicules dans leur environnement réel : concession, stock, atelier et transport. C’est ce qui permet de voir concrètement le produit et son gabarit.</p><div className={styles.realTags}><b>Stock réel</b><b>Préparation</b><b>Livraison</b></div></div><div className={styles.realGrid}><img src={RAW+"/real/stock-couleurs.webp"} alt="Stock réel NeoDrive"/><img src={RAW+"/real/devant-atelier.webp"} alt="NeoDrive devant atelier"/><img src={RAW+"/real/livraison-transporteur.webp"} alt="Transport NeoDrive"/></div></section>
<section className={styles.interior}><div className={styles.interiorPhoto}><img src={RAW+"/gallery/interieur.svg"} alt="Intérieur réel de la NeoDrive SWITCH"/></div><div><span className={styles.eyebrow}>À L’INTÉRIEUR</span><h2>Deux vraies places. Un habitacle simple et pratique.</h2><p>Une position de conduite dégagée, des commandes accessibles et les équipements utiles pour les déplacements du quotidien.</p><div className={styles.featureGrid}><span>✓ Autoradio</span><span>✓ Bluetooth & USB</span><span>✓ Chauffage</span><span>✓ Caméra de recul</span><span>✓ Aide au stationnement</span><span>✓ Ventilation</span></div></div></section>
<section className={styles.steel}><div><span className={styles.eyebrow}>STRUCTURE ET CARROSSERIE EN ACIER</span><h2>Compacte dehors. Rassurante au quotidien.</h2><p>La NeoDrive SWITCH privilégie une conception simple et une carrosserie acier. Son petit gabarit facilite le stationnement tout en conservant un véritable habitacle deux places.</p></div><div className={styles.steelFacts}><article><b>2,50 m</b><span>de longueur</span></article><article><b>100 % électrique</b><span>recharge sur prise 220 V</span></article><article><b>45 km/h</b><span>format voiture sans permis</span></article></div></section>
<section className={styles.versions}><div className={styles.heading}><span className={styles.eyebrow}>CHOISISSEZ VOTRE VERSION</span><h2>Un prix clair. Des équipements selon vos besoins.</h2></div><div className={styles.versionGrid}><article><span>VERSION ESSENTIELLE</span><h3>3 990 € TTC</h3><p>Pour aller à l’essentiel avec une voiture électrique neuve.</p><ul><li>Véhicule électrique neuf</li><li>Batterie incluse</li><li>Chargeur 220 V inclus</li><li>Deux places</li></ul></article><article className={styles.comfort}><span>VERSION CONFORT</span><h3>4 990 € TTC</h3><p>Davantage d’équipements pour une utilisation quotidienne plus agréable.</p><ul><li>Caméra et aide au stationnement</li><li>Chauffage et ventilation de toit</li><li>Autoradio, Bluetooth et USB</li><li>Alarme antivol et assistance en côte</li></ul></article></div></section>
<section className={styles.specSection}><div className={styles.heading}><span className={styles.eyebrow}>CARACTÉRISTIQUES</span><h2>L’essentiel, clairement.</h2></div><div className={styles.specs}>{specs.map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div><p className={styles.note}>L’autonomie réelle varie selon la température, le relief, la charge, la vitesse et le style de conduite.</p></section>
<section className={styles.delivery}><img src={RAW+"/real/livraison-transporteur.webp"} alt="Livraison de voitures NeoDrive"/><div><span className={styles.eyebrow}>DE NOTRE STOCK JUSQU’À CHEZ VOUS</span><h2>Une livraison organisée par NeoDrive.</h2><p>Nous organisons le transport de votre voiture et restons votre interlocuteur pour la préparation, la livraison et l’accompagnement.</p><a href="https://wa.me/33628261446?text=Bonjour%2C%20je%20souhaite%20conna%C3%AEtre%20les%20NeoDrive%20disponibles" target="_blank" rel="noreferrer">Voir les disponibilités</a></div></section>
{zoom&&<div className={styles.overlay} onClick={()=>setZoom(false)}><img src={photos[index][0]} alt={photos[index][2]}/><button aria-label="Fermer">×</button></div>}</main>}
