"use client";
import{useState}from"react";import styles from"./produit.module.css";
const photos=[["/neodrive-switch/real/exterieur-avant.webp","Vue avant de la NeoDrive SWITCH"],["/neodrive-switch/real/exterieur-ville.webp","NeoDrive SWITCH en environnement urbain"],["/neodrive-switch/real/exterieur-arriere.webp","Vue arrière de la NeoDrive SWITCH"],["/neodrive-switch/real/interieur-tableau-de-bord.webp","Tableau de bord et intérieur"],["/neodrive-switch/real/devant-atelier.webp","NeoDrive SWITCH devant un atelier automobile"],["/neodrive-switch/real/livraison-transporteur.webp","Livraison des voitures NeoDrive"],["/neodrive-switch/real/stock-couleurs.webp","Stock de voitures NeoDrive"]];
const specs=[["Moteur","3 kW électrique"],["Vitesse maximale","45 km/h"],["Autonomie indicative","50 à 70 km"],["Recharge","Prise 220 V — environ 6 h"],["Capacité","2 places"],["Dimensions","2,50 × 1,30 × 1,65 m"]];
export default function Produit(){const[index,setIndex]=useState(0);const[zoom,setZoom]=useState(false);const move=(d:number)=>setIndex((index+d+photos.length)%photos.length);return <main className={styles.page}>
<section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>VOITURE SANS PERMIS · 100 % ÉLECTRIQUE</span><h1>NeoDrive<br/><em>SWITCH</em></h1><p>Une vraie voiture électrique deux places, compacte, accessible et pensée pour simplifier tous vos déplacements quotidiens.</p><div className={styles.price}><span>À partir de</span><strong>3 990 € TTC</strong></div><div className={styles.actions}><a href="https://wa.me/33628261446?text=Bonjour%2C%20je%20souhaite%20recevoir%20une%20vid%C3%A9o%20de%20la%20NeoDrive%20SWITCH" target="_blank">Recevoir une vidéo</a><a className={styles.secondary} href="/contact">Être rappelé</a></div><small>Prix selon version, équipement et disponibilité.</small></div><div className={styles.heroPhoto}><img src={photos[0][0]} alt={photos[0][1]}/><div><b>2 places</b><b>45 km/h</b><b>Recharge 220 V</b></div></div></section>
<section className={styles.reassurance}><article><b>Véhicule neuf</b><span>Préparé avant livraison</span></article><article><b>Paiement à la livraison</b><span>Après réception et contrôle</span></article><article><b>Livraison à domicile</b><span>Jusqu’à votre porte</span></article><article><b>Accompagnement NeoDrive</b><span>Conseil, pièces et assistance</span></article></section>
<section className={styles.gallerySection}><div className={styles.heading}><span className={styles.eyebrow}>LE VÉHICULE RÉEL</span><h2>Regardez-la sous tous les angles.</h2><p>Extérieur, intérieur, atelier et livraison : toutes les photos présentées ici sont des photos réelles de nos véhicules.</p></div><div className={styles.viewer}><div className={styles.stage}><img src={photos[index][0]} alt={photos[index][1]} onClick={()=>setZoom(true)}/><button className={styles.prev} onClick={()=>move(-1)}>‹</button><button className={styles.next} onClick={()=>move(1)}>›</button><span>{index+1} / {photos.length}</span></div><div className={styles.thumbs}>{photos.map(([src,alt],i)=><button key={src} className={i===index?styles.active:""} onClick={()=>setIndex(i)}><img src={src} alt={alt}/></button>)}</div></div></section>
<section className={styles.interior}><div className={styles.interiorPhoto}><img src="/neodrive-switch/real/interieur-tableau-de-bord.webp" alt="Intérieur et tableau de bord NeoDrive SWITCH"/></div><div><span className={styles.eyebrow}>UN VRAI HABITACLE</span><h2>Simple, lumineux et facile à prendre en main.</h2><p>Commandes accessibles, position de conduite dégagée et équipements utiles : tout est organisé pour une conduite quotidienne sans complication.</p><div className={styles.featureGrid}><span>✓ Autoradio</span><span>✓ Enceintes</span><span>✓ Bluetooth & USB</span><span>✓ Chauffage</span><span>✓ Caméra de recul</span><span>✓ Aide au stationnement</span></div></div></section>
<section className={styles.steel}><div><span className={styles.eyebrow}>STRUCTURE ET CARROSSERIE EN ACIER</span><h2>Une conception robuste, faite pour durer.</h2><p>Contrairement à de nombreuses voiturettes en plastique, la NeoDrive SWITCH privilégie l’acier pour sa structure et sa carrosserie.</p></div><div className={styles.steelFacts}><article><b>Compacte</b><span>Facile à garer et à manœuvrer</span></article><article><b>Électrique</b><span>Silencieuse et simple à recharger</span></article><article><b>Accessible</b><span>Une voiture neuve à prix contenu</span></article></div></section>
<section className={styles.versions}><div className={styles.heading}><span className={styles.eyebrow}>CHOISISSEZ VOTRE VERSION</span><h2>L’essentiel ou le maximum d’équipements.</h2></div><div className={styles.versionGrid}><article><span>VERSION ESSENTIELLE</span><h3>3 990 € TTC</h3><p>La voiture neuve, sa batterie et son chargeur 220 V.</p><ul><li>Véhicule électrique neuf</li><li>Batterie incluse</li><li>Chargeur 220 V inclus</li><li>Deux places</li></ul></article><article className={styles.comfort}><span>PACK CONFORT · + 999 € TTC</span><h3>Équipée pour le quotidien</h3><p>Un maximum d’équipements de confort et de sécurité.</p><ul><li>Caméra et aide au stationnement</li><li>Chauffage et ventilation de toit</li><li>Autoradio, enceintes, Bluetooth et USB</li><li>Alarme antivol et assistance en côte</li><li>Toit ouvrant, pare-soleil et enjoliveurs</li></ul></article></div></section>
<section className={styles.specSection}><div className={styles.heading}><span className={styles.eyebrow}>CARACTÉRISTIQUES</span><h2>L’essentiel, clairement.</h2></div><div className={styles.specs}>{specs.map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div><p className={styles.note}>L’autonomie varie selon la température, le relief, la charge, la vitesse et le style de conduite.</p></section>
<section className={styles.delivery}><img src="/neodrive-switch/real/livraison-transporteur.webp" alt="Livraison d’une voiture NeoDrive"/><div><span className={styles.eyebrow}>LIVRÉE JUSQU’À VOTRE PORTE</span><h2>Aucun acompte avant réception.</h2><p>Vous payez uniquement à la livraison, après avoir reçu et contrôlé votre voiturette avec notre transporteur.</p><a href="https://wa.me/33628261446?text=Bonjour%2C%20je%20souhaite%20conna%C3%AEtre%20les%20NeoDrive%20disponibles" target="_blank">Voir les disponibilités</a></div></section>
{zoom&&<div className={styles.overlay} onClick={()=>setZoom(false)}><img src={photos[index][0]} alt={photos[index][1]}/><button>×</button></div>}</main>}
